language: generic

deploy:
  provider: s3
  access_key_id:
    secure: "fu4zlifjqmetcEPdZOitV9NkO+MdIWNJp2IV6/Z8Q0sw4EZkMNyIW2J5M2AI1NUD2ngKTP76HOlCZzezZI6nXI5s4+NTaEdLMZxN++zzYbFqn64MdanrUL2b2kTEugI/MK6zon/ei4IuPj33AaC9gYAug+TO3KJJVS/iXuJ9K6ZTaXONdlF4nyHFqHzIFcyvUwEDz9S5JKD+i05WWT954VfbC755xq0dao0OhHEKfFlT8VmkgyXKpOrSsS90zqrNX6YTRJNaFbADCI0vVm6ZjyOJnqu9JOkANQfetQG0CelWM3U1X2c8GFvWCRTxjjA0O5Q522rkP+H6Vs2pOnnOoaxnZxsjDYpkbIgMy4ah8iSDSfENreH2q/T9ndyxLNyvLPk4QgRCe0uiBwFNLIsRQRjcVlMX9b9y2OCC5unmE0ssQA5w6HuM0BOqOiAwNtfoTswqklxyWAleMO0rLqwuJShPVP4MJ1OW4gPcLSWqfCt1IraScoKFAur1x8eAY6D+0+jY6ErIZDn4NIBVRGGUDGkiyTAbmjpBG86u8DXoXmjC9BA27xLYfzl6ioFeTxBMJYLomuzQYOFygT4Hnro44QwS5BPeWbowWUyilqbn2eR+DRbwq/PFZvrDhPwQ5EIfHs0EexZlE+FD3DD6yw5Pg09QY7+u7ayGnTZcgigRrsg="
  secret_access_key:
    secure: "eBf09O8s5S3P5lWVtsJb7XVFpzCq2v4RstglKrbkvTpeaIfqbK38dta7ma63Tl1+708DOKPweu3YyGKoI4osnvGz8YIisJRGhMU+fOuDoCy/DvXdLlybtp2dZ25uMTw90B06nhPzQZJ7CYm9aLbSiBHQZJYkERUTvQAiR6dCJr3Y2TwC+Ey6nznbEuriEIbm/UoFea3xD9u28p1HGhEXDeIW3vcJDdLb1ubvQwfVWyQqo862xr33+9OFOSgVPY1vCzqgglhJRSs3eCC939lV/CDWKZpNBMsNNiRBnsCNwAQQkk04lGfaswQ4PHIWvT9T/RqCxR8IX0Gi4gtG5IoPcZqclMH9iNEU7Zqis+aFtiHbfau1GzzmQEXfZn7Y+2ULrbvNg2SBjulswoQC9l0O4E/DjcOW2cKx7zHxQw6pYvqwV9SE9s8l2FoQME2k5sVX++Onmkq6I7S9oXB81sr3hjbuOTLocy6SUjrfCeDsY3vv1TnD8EdMVaxNen+QNTM9GKiK07XwfSE4qjiM2E4YyhURKs8fbipwHHxgwASTnmV4SWyh8w0fDwLcaPyEUT7dOawchnm0micBhXA/j7JbfzN+YWkqcNYD43yXffyReKxdbcD7pclAOOq4ABFk8dKnNmvmVAE45bmBLal43yDJl9G7DYCQJbCrBeP8bQ170i4="
  bucket: andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: www
  upload_dir: projects/vta-tracker
